apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tjg8w3kn3-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tjg8w3kn3-nodejs 
  name: tjg8w3kn3-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tjg8w3kn3-nodejs 
